name: amaliy
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  change_app_package_name: ^1.1.0
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_analytics: ^10.4.4
  firebase_storage: ^11.2.5
  provider: ^6.0.5
  http: ^1.1.0
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.4
  image_picker: ^1.0.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  like_button: ^2.0.5
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
